// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptBank.Data;

#nullable disable

namespace PromptBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421080519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("PromptBank.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Explain the following code step by step, including what each section does and why it matters:\n\n```\n{{code}}\n```",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = true,
                            OwnerName = "Dev Team",
                            RatingCount = 10,
                            RatingTotal = 45,
                            Title = "Explain code"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Write xUnit unit tests for the following method. Cover happy path, edge cases, and error conditions:\n\n```\n{{method}}\n```",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = true,
                            OwnerName = "QA Team",
                            RatingCount = 9,
                            RatingTotal = 38,
                            Title = "Write unit tests"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Review the following code for: correctness, security issues, performance, readability, and adherence to SOLID principles. Provide specific suggestions:\n\n```\n{{code}}\n```",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = false,
                            OwnerName = "Architecture Guild",
                            RatingCount = 5,
                            RatingTotal = 20,
                            Title = "Code review checklist"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Write a SQL query to {{task}}. The table schema is:\n\n{{schema}}\n\nOptimise for readability and performance.",
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = false,
                            OwnerName = "Data Team",
                            RatingCount = 4,
                            RatingTotal = 12,
                            Title = "Generate SQL query"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Summarise the following pull request diff in plain English. Include what changed, why it matters, and any potential risks:\n\n{{diff}}",
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = false,
                            OwnerName = "Platform Team",
                            RatingCount = 3,
                            RatingTotal = 8,
                            Title = "Summarise PR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
